MYSQL_HOST = 'fall19-ssdi-project-group5-db.cz4afuqpuil9.us-east-2.rds.amazonaws.com'
MYSQL_USER = 'Project_root'
MYSQL_PASSWORD = 'Frank3nst3In_18'
MYSQL_DB = 'EVENT_BASED_CARPOOLING'
MYSQL_DB_TEST = 'EVENT_BASED_CARPOOLING_TEST'
MYSQL_CURSORCLASS = 'DictCursor'
JWT_SECRET_KEY = 'secret'